#!/bin/bash
"exec" "snakemake" "--printshellcmds" "--cores" "20" "--snakefile" "$0" "--jobs" "10"

import glob
import os.path
import itertools

SOURCE_DIR = '../../_m'
EXT = '.bam'


def sample_dict_iter(path, ext):
    for filename in glob.iglob(path+'/*'+ext):
        sample = os.path.basename(filename)[:-len(ext)]
        yield sample, {'filename': filename}
		

SAMPLE_DICT = {k:v for k,v in sample_dict_iter(SOURCE_DIR, EXT)}


rule all:
    input:
        expand('../_m/{sample}.bam.bai', sample=SAMPLE_DICT.keys())

	
rule samtools_sort:
    input:
        lambda x: SAMPLE_DICT[x.sample]['filename']
    output:
        '../_m/{sample}.bam'
    log:
        '../_m/{sample}.samtools_sort.stderr'
    threads: 20
    shell:
        '( '
        'samtools sort '
        '-o {output} '
        '-m 3G '
        '--threads {threads} '
        '{input} '
	') 2>&1 > {log}'


rule samtools_index:
    input:
        '../_m/{sample}.bam'
    output:
        '../_m/{sample}.bam.bai'
    log:
        '{sample}.samtools_index.stderr'
    threads: 2
    shell:
        '( '
        'samtools index {input} '
	') 2>&1 > {log}'
