#!/bin/bash
"exec" "snakemake" "--keep-going" "--printshellcmds" "--jobs" "12" "--snakefile" "$0"

import glob
import os
import re

def get_sample_data():
    ext1 = "_1.fastq.gz"
    ext2 = "_2.fastq.gz"
    src_dir = "../../raw_data/fastq/*/_m"

    
    for x in glob.glob("%s/*%s" % (src_dir, ext1)):
        sample_name = os.path.basename(x)[:-len(ext1)]
        yield (sample_name,
               {
                   'R1' : x,
                   'R2' : (re.sub(ext1,ext2,x))
               }
              )

        
        
sample_dict = dict(get_sample_data())



rule all:
    input:
        expand('{sample}.bam', sample=sample_dict.keys())


       

rule hisat2:
    input:
        r1 = lambda w: sample_dict[w.sample]['R1'],
        r2 = lambda w: sample_dict[w.sample]['R2'],

    output:
        '{sample}.bam'
    
    params:
        r1 = lambda w: sample_dict[w.sample]['R1'],
        r2 = lambda w: sample_dict[w.sample]['R2'],
    log:
        stdout = '{sample}.stdout',
        stderr = '{sample}.stderr',
    shell:
        """ ( hisat2 \
        --dta \
        --time \
        --threads 1 \
        -x /ceph/genome/human/gencode37/GRCh38.p13.PRI/genome_with_xdp_sva/gtf.PRI/hisat2/_m/GRCh38_with_XDP_SVA.primary_assembly.genome \
        -1 {input.r1} \
        -2 {input.r2} \
        | samtools view -u - \
        | samtools sort -o {output} -m 3G --threads 1 -
) \
        > {log.stdout} 2> {log.stderr}
        """
        
